# Classification

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head(5)

,Date,Platform,Text,Person,Truthfulness_Category
0,"December 3, 2022",a Truth Social post:,“The revelation of massive & widespread fraud ...,Donald Trump,Pants on Fire
1,"November 28, 2022",a post:,The 2021 infrastructure bill requires all new ...,Instagram posts,Mostly False
2,"November 27, 2022",an interview on CNN:,“60% of counties in this country are refusing ...,Chris Murphy,NaN
3,"November 22, 2022",Public statement:,“A lot of the programs (that were) started dur...,Robin Vos,Mostly False
4,"November 17, 2022",a post:,“Joe Biden is being investigated for human tra...,Instagram posts,False

In [4]:
i = df[((df.Truthfulness_Category == 'NaN'))].index
df.drop(i)

,Date,Platform,Text,Person,Truthfulness_Category
0,"December 3, 2022",a Truth Social post:,“The revelation of massive & widespread fraud ...,Donald Trump,Pants on Fire
1,"November 28, 2022",a post:,The 2021 infrastructure bill requires all new ...,Instagram posts,Mostly False
2,"November 27, 2022",an interview on CNN:,“60% of counties in this country are refusing ...,Chris Murphy,NaN
3,"November 22, 2022",Public statement:,“A lot of the programs (that were) started dur...,Robin Vos,Mostly False
4,"November 17, 2022",a post:,“Joe Biden is being investigated for human tra...,Instagram posts,False
...,...,...,...,...,...
5250,"August 31, 2008",a chain e-mail:,"""While Sarah was Mayor of Wasilla she tried to...",Chain email,NaN
5251,"August 31, 2008",in an e-mail message:,"Palin ""fired Wasilla's Police Chief because he...",Chain email,Mostly True
5252,"August 31, 2008",a chain e-mail:,"Palin ""inherited a city with zero debt, but le...",Chain email,Mostly True
5253,"September 8, 2008",a TV ad:,"John McCain ""took on the drug industry.""",John McCain,Mostly True
5254,,NaN,NaN,NaN,NaN

In [5]:
df2=df.dropna()
df2=df.dropna(axis=0)

In [6]:
df2.head(5)

,Date,Platform,Text,Person,Truthfulness_Category
0,"December 3, 2022",a Truth Social post:,“The revelation of massive & widespread fraud ...,Donald Trump,Pants on Fire
1,"November 28, 2022",a post:,The 2021 infrastructure bill requires all new ...,Instagram posts,Mostly False
3,"November 22, 2022",Public statement:,“A lot of the programs (that were) started dur...,Robin Vos,Mostly False
4,"November 17, 2022",a post:,“Joe Biden is being investigated for human tra...,Instagram posts,False
5,"November 19, 2022",a speech:,Herschel Walker “wants a nationwide ban on abo...,Raphael Warnock,Mostly True

In [7]:
df2['Truthfulness_Category'] = df2['Truthfulness_Category'].replace(['Mostly False'],'False')
df2['Truthfulness_Category'] = df2['Truthfulness_Category'].replace(['Pants on Fire'],'False')
df2['Truthfulness_Category'] = df2['Truthfulness_Category'].replace(['Mostly True'],'True')

In [8]:
df2.head(5)

,Date,Platform,Text,Person,Truthfulness_Category
0,"December 3, 2022",a Truth Social post:,“The revelation of massive & widespread fraud ...,Donald Trump,False
1,"November 28, 2022",a post:,The 2021 infrastructure bill requires all new ...,Instagram posts,False
3,"November 22, 2022",Public statement:,“A lot of the programs (that were) started dur...,Robin Vos,False
4,"November 17, 2022",a post:,“Joe Biden is being investigated for human tra...,Instagram posts,False
5,"November 19, 2022",a speech:,Herschel Walker “wants a nationwide ban on abo...,Raphael Warnock,True

In [9]:
for col in df2.columns:
    print(col)
    
df2 = df2.drop(['Date','Platform','Person'], axis=1)
df2

Date
Platform
Text
Person
Truthfulness_Category

                                                   Text Truthfulness_Category
0     “The revelation of massive & widespread fraud ...                 False
1     The 2021 infrastructure bill requires all new ...                 False
3     “A lot of the programs (that were) started dur...                 False
4     “Joe Biden is being investigated for human tra...                 False
5     Herschel Walker “wants a nationwide ban on abo...                  True
...                                                 ...                   ...
5247  Obama's one education accomplishment was "legi...                 False
5248               Says Obama called Sarah Palin a pig.                 False
5251  Palin "fired Wasilla's Police Chief because he...                  True
5252  Palin "inherited a city with zero debt, but le...                  True
5253           John McCain "took on the drug industry."                  True

[4160 rows x 2 columns]

In [10]:
df2['Truthfulness_Category'] = df2['Truthfulness_Category'].map({'False':0,'True':1})
df2

                                                   Text  Truthfulness_Category
0     “The revelation of massive & widespread fraud ...                    0.0
1     The 2021 infrastructure bill requires all new ...                    0.0
3     “A lot of the programs (that were) started dur...                    0.0
4     “Joe Biden is being investigated for human tra...                    0.0
5     Herschel Walker “wants a nationwide ban on abo...                    1.0
...                                                 ...                    ...
5247  Obama's one education accomplishment was "legi...                    0.0
5248               Says Obama called Sarah Palin a pig.                    0.0
5251  Palin "fired Wasilla's Police Chief because he...                    1.0
5252  Palin "inherited a city with zero debt, but le...                    1.0
5253           John McCain "took on the drug industry."                    1.0

[4160 rows x 2 columns]

In [11]:
# df2 = df2.reset_index()
df2=df2.dropna()
df2=df2.dropna(axis=0)

In [12]:
check_nan1 = df2['Text'].isnull().values.any()
check_nan2 = df2['Truthfulness_Category'].isnull().values.any()
# printing the result
print(check_nan1)
print(check_nan2)

False
False

In [13]:
df2

                                                   Text  Truthfulness_Category
0     “The revelation of massive & widespread fraud ...                    0.0
1     The 2021 infrastructure bill requires all new ...                    0.0
3     “A lot of the programs (that were) started dur...                    0.0
4     “Joe Biden is being investigated for human tra...                    0.0
5     Herschel Walker “wants a nationwide ban on abo...                    1.0
...                                                 ...                    ...
5247  Obama's one education accomplishment was "legi...                    0.0
5248               Says Obama called Sarah Palin a pig.                    0.0
5251  Palin "fired Wasilla's Police Chief because he...                    1.0
5252  Palin "inherited a city with zero debt, but le...                    1.0
5253           John McCain "took on the drug industry."                    1.0

[4157 rows x 2 columns]

In [14]:
X = df2['Text']
y = df2['Truthfulness_Category']
X=np.array(X)
y=np.array(y)
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y)

In [15]:
X_train

array(['"Forty-five percent of those who\'ve been unemployed, they\'ve been unemployed for six months or longer."',
       '"Taxpayer-funded benefits to illegals" in California are "a skyrocketing cost under Obamacare."',
       '"We have flown a Boeing 737 across the Atlantic Ocean on biofuels. We have flown F-18s."',
       ...,
       'Foreign aid "is less than 1 percent of our federal budget."  ',
       '"Republican leadership took the lead confirming Loretta Lynch as attorney general."',
       'Says the goal of the Affordable Care Act was to get 30 million people insured, but it only got 7 million.'],
      dtype=object)

In [16]:
counter = CountVectorizer()
counter.fit(X_train)

counts_train = counter.transform(X_train)#transform the training data
counts_test = counter.transform(X_test)#transform the testing data

# MLP Classifier

In [50]:
#create the MLP classifier
clf = MLPClassifier(solver='adam', alpha=0.0001, hidden_layer_sizes=(100,),
                    learning_rate="constant", activation='relu', random_state=10, max_iter=6)
#fit the model
clf.fit(counts_train,y_train)
#make prediction
counts_test_predict = clf.predict(counts_test)
counts_test_pred = np.reshape(counts_test_predict, (len(counts_test_predict), 1))
#get the accuracy score
accuracy_score(y_test, counts_test_pred)

0.7051282051282052

#Accuracy is 70.51%